lprint.c: Enable TLS support in Web UI
michaelrsweet/lprint pull request #151
Opened 2024-07-30 14:36 UTC by zdohnal

Currently (1.3.1) there is no way how to turn TLS web UI pages, because system callback does not set WEB_TLS option by default, and checks only for `no-tls` when processing server options.

This can be fixed by two way, depending on which default settings we prefer. The PR enables TLS pages by default, leaving to user whether he wants them to be disabled.

Do let me know if you would prefer the other way around.

2024-07-30 19:59 UTC, michaelrsweet requested changes
Should probably enable by default but disable when the "no-tls" option is used.

2024-08-21 01:11 UTC, michaelrsweet commented on lprint.c
> +        soptions &= (pappl_soptions_t)~PAPPL_SOPTIONS_WEB_TLS;
So you need to remove/mask WEB_TLS and add NO_TLS, since the "no-tls" option disables TLS entirely, not just the TLS certificate web page.

2024-08-21 01:11 UTC, michaelrsweet requested changes
Need a little cleanup but otherwise +1

2024-08-30 06:32 UTC, zdohnal commented
I was not able to come up with one line expression which would be readable for me, feel free to check.

2024-09-04 19:26 UTC, michaelrsweet requested changes

2024-09-04 19:26 UTC, michaelrsweet commented on lprint.c
> +      {
```c
soptions = (pappl_soptions_t)((soptions | PAPPL_SOPTIONS_NO_TLS) & ~PAPPL_SOPTIONS_WEB_TLS);
```

2024-10-17 08:31 UTC, zdohnal commented on lprint.c
> +      {
Updated, sorry for the delay.

2024-11-14 01:05 UTC, michaelrsweet approved these changes

2024-11-14 01:08 UTC, merged