Systemd related changes
michaelrsweet/lprint pull request #50
Opened 2022-01-04 12:56 UTC by zdohnal

- enable possibility to turn off systemd unit file's installation
  (some distitributions can still work without systemd)
- enable possibility to add a specific path to systemd unit dir
  via UNITDIR variable (if not used, /usr/lib/systemd/system is chosen)
- install lprint.service into /usr/lib/systemd/system by default -
  /etc/systemd/system is for admin's overrides

2022-01-04 13:48 UTC, michaelrsweet requested changes
@zdohnal So I think AC_ARG_WITH (as in `--with-systemd[=PATH]`) would be more appropriate, and in the makefile the "else" should be changed to an "elif" with the condition that `$(unitdir)` isn't empty allowing `--without-system` to be supported.

Also, shouldn't we be using `${libdir}/systemd/...` for the default path and not hardcoding to `/usr/lib/systemd`? It's fine for a system package to put things in /usr but most local/site installs use `/usr/local` (default prefix) or `/opt` (FHS).

2022-01-05 06:16 UTC, zdohnal commented
> @zdohnal So I think AC_ARG_WITH (as in `--with-systemd[=PATH]`) would be more appropriate,

TBH setting the path via configuration option looked as an overkill for me (AFAIK if someone installs systemd, its system service files would lie in /usr/lib/systemd/system), so env variable looked fine for such a corner case.

> and in the makefile the "else" should be changed to an "elif" with the condition that `$(unitdir)` isn't empty allowing `--without-system` to be supported.

Ah, this one I've missed - that's what I get from switching from one thing to another... thx.

> 
> Also, shouldn't we be using `${libdir}/systemd/...` for the default path and not hardcoding to `/usr/lib/systemd`? It's fine for a system package to put things in /usr but most local/site installs use `/usr/local` (default prefix) or `/opt` (FHS).

Using ```${libdir}``` would result into ```/usr/[local/]lib64``` on 64b archs and systemd (CUPS does behave in similar way :) ) looks only into ```/usr/[local/]lib/systemd/system```. So we can use the prefix, but not ```${libdir}``` (IIUC).

2022-01-18 00:59 UTC, michaelrsweet approved these changes
I'll do a little cleanup for cross-compilation, but otherwise LGTM.

2022-01-18 01:00 UTC, merged

2022-01-18 05:26 UTC, zdohnal commented
Thank you for looking into it! :)